### ISSUE TITLE
Questions in regards to checkpoints

### ISSUE THREAD

**Issue by himcha-ni** [stdcoutzrh/BuildingExtraction#3]
Hi. Thank you for your great work!
I am trying to reproduce your results, but I am encountering some issues regards to checkpoints. 

First of all, when I run the code with setting pretrained = True, i get 
'''
File "/home/himcha/.local/lib/python3.8/site-packages/pytorch_lightning/core/saving.py", line 204, in _load_model_state                                                         
    keys = model.load_state_dict(checkpoint["state_dict"], strict=strict)                                                                                                             
**KeyError: 'state_dict'** 
'''
Is there a way to avoid this error? It seems like the error is bypassed when I set 
keys = model.load_state_dict(checkpoint, strict=False), but it doesn't seem like a right way to handle it.

Also, it seems like the key lengths of the dictionary in models/SDSCUNet.py doens't match.
I am currently using ckpt_T.pth from https://github.com/OliverRensu/Shunted-Transformer. Am I using the correct checkpoint? Furthermore, is it meaningful to use ckpt_S, or ckpt_B.pth for the pretrained backbone?

Lastly, would it be okay to get the "sdscunet-epoch105-bz8-0203" checkpoint via email? 
It would be great if I can compare my results with yours. Thank you!

**Comment by stdcoutzrh** [comment]
Hi,himcha.Thank you for your interest in our work！
I rerun the code, but I did not encounter the problem you described.You can first run the main function in SDSCUNet.py （python geoseg/models/SDSCUNet.py）separately, set the pre trained on line 686 to True, and change the path of the weight to your path. Under normal circumstances, the following content will be output：
```shell
current model Params: 21.3197 M
pretrained_path:/mnt/sdb/zrh/ckpt/ckpt_T.pth
368
529
torch.Size([1, 6, 512, 512])
```
Secondly, this may also be an error caused by version differences. My torch is 1.11.0 and pytorch-lightning  is 1.5.9.I am using Ckpt_ T.

you can download sdscunet-epoch105-bz8-0203.ckpt (on inria dataset) from here:
[https://drive.google.com/file/d/1s1lX11RCajm3EnbMshab_13hGLbKVgiN/view?usp=drive_link](https://drive.google.com/file/d/1s1lX11RCajm3EnbMshab_13hGLbKVgiN/view?usp=drive_link)

If you have any further questions, please continue to leave a message. Thank you.

**Comment by himcha-ni** [comment]
Thank you for your kind explanation. 

The SDSCUNet.py does show the upper output, but with other unsupported operator counts. Is this normal..?
```
`Unsupported operator aten::add_ encountered 1 time(s)
Unsupported operator aten::gelu encountered 44 time(s)
Unsupported operator aten::mul encountered 66 time(s)
Unsupported operator aten::softmax encountered 33 time(s)
Unsupported operator aten::add encountered 84 time(s)
Unsupported operator aten::mean encountered 3 time(s)
Unsupported operator aten::mul_ encountered 8 time(s)
The following submodules of the model were never called during the trace of the graph. They may be unused, or they were accessed by direct calls to .forward() or via other python methods. In the latter case they will have zeros for statistics, though their statistics will still contribute to their parent calling module.
shunted_unet.patch_expand1`
```

Also, about created image patches, which one should I run first? inria_patch_split.py or split_1500_into_512.py? Maybe that's causing some misc errors.

Just checked my versions, and torch is 2.0.1, while pytorch-lightning is 1.5.9. Let me try some other configurations to resolve the upper keyerror.

Once again, thank you for your support.

**Comment by stdcoutzrh** [comment]
Hi,sorry for late reply.

"Unsupported operator... "is the normal output, which is the warning message output by fvcore when calculating the FLOPs and it is not an error.

When processing data, for the two datasets, you can directly refer to the method of [buildformer](https://github.com/WangLibo1995/BuildFormer) first. You only need to run inria_patch_split.py to process the inria dataset. 

Split_ 1500_ Into_ 512.py is only used for the mass dataset, mainly because our model currently only supports 512x512 inputs.
