### ISSUE TITLE
Questions about the training process of SDSC-Unet

### ISSUE THREAD

**Issue by chenbaiyubk** [stdcoutzrh/BuildingExtraction#4]
Hi, thank you for your great work.  
During the model training process, every epoch takes about ten minutes, is that normal? I used the same graphics card and training parameters.

**Comment by stdcoutzrh** [comment]
Hello, if it's an inria dataset, I think it's normal because this dataset is relatively large. In addition, the backbone of our model is the Shunted Transformer. Although its computational complexity and model parameters are relatively low, the actual inference speed seems to be less advantageous compared to Swin Transformer and other ViT backbones. If the loss decreases normally and the iou increases normally, then there should be no problem with training.

**Comment by chenbaiyubk** [comment]
Thank you for the response.
I use the WHU building dataset, the actual inference time is almost 2 times longer than DSAT-Net and BuildFormer.
